name: NSE Data Automation

on:
  workflow_dispatch: # Sirf manual aur cron-job.org ke signal par chalega

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests pandas

      - name: Run Automation
        env:
          GOOGLE_WEBAPP_URL: ${{ secrets.GOOGLE_WEBAPP_URL }}
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
        run: python main.py
